spring:
  application:
    name: group-investment

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDS_URL}?serverTimezone=Asia/Seoul
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  ag:
    url: ${ARMAGYETDON_URL}

  tg:
    url: ${CLIENT_URL}

  devtools:
    restart:
      enabled: true # auto restart
      additional-exclude: static/**,public/**

  jwt:
    secret: ${JWT_SECRET}

  rabbitmq:
    host: ${MQ_HOST}
    port: ${MQ_PORT}
    username: ${MQ_USERNAME}
    password: ${MQ_PASSWORD}
    exchange:
      name: (AMQP default)
    fcm-queue:
      name: main_to_alarm
    main-stock-queue:
      name: offer_to_trade
    vote-alarm-queue:
      name: vote_to_alarm
    rule-alarm-queue:
      name: rule_to_alarm

server:
  port: 8081

logging:
  level:
    root: info
